### ISSUE TITLE
Cert-viewer Installation on Windows 10

### ISSUE THREAD

**Issue by Pasayadaan** [digital-certificates/cert-viewer#24]
For Quick Start installation suggestions for Windows 10 
1. It may be a good idea to mention in installation document to disable Hyper-v on Windows 10 for docker to run
2. docker-machine ip should be executed first as after docker-compose up there is no way to check ip on that prompt and unless another docker quickstart terminal is started to check ip.

**Comment by kimdhamilton** [comment]
These are great suggestions, thank you. Btw, did this work for you on Windows 10, with the exception of the above issues?

**Comment by Pasayadaan** [comment]
Yes it did work on Windows 10. Assuming that the sample certificate entered is fake I got [Failed] for the last 2 steps of verification and "Not Verified" status.

One more suggestion in installation doc 
"after installing docker and checking machine ip, change folder to cert-viewer before running docker-compose build". Similar instruction has been mentioned in cert-issuer installation (cd cert-issuer step 3) which is missing in cert-viewer Quick Start.

**Comment by kimdhamilton** [comment]
Yes, the sample certificate will fail the last 2 steps with the current sample data.

I will update 2 of the 3 items:

- rearrange docker-machine ip step in instructions
- change folder to cert-viewer

I'm not adding the mention of Hyper-v on Windows 10 because:
1. it's specific to Docker/Windows 10 (not this app)
2. based on a quick search it seemed inconclusive if we want to issue this as guidance. I saw mention of workarounds. I am not sure if these work, but see #1.
